version: '3.4'

services:
  longrunningjobui:
    image: longrunningjobui
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 1000:1000
